/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discussions` | `/discussions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigateur` | `/navigateur`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/temoignages` | `/temoignages`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discussions` | `/discussions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigateur` | `/navigateur`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/temoignages` | `/temoignages`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discussions${`?${string}` | `#${string}` | ''}` | `/discussions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigateur${`?${string}` | `#${string}` | ''}` | `/navigateur${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/temoignages${`?${string}` | `#${string}` | ''}` | `/temoignages${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discussions` | `/discussions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigateur` | `/navigateur`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/temoignages` | `/temoignages`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
